### ISSUE TITLE
Error when first line of test module contains docstring !<

### ISSUE THREAD

**Issue by DaanVanVugt** [acroucher/FRUITPy#10]
Hi,

I ran into a weird error when using FRUITPy: If the first line (before module) contains a comment (of the form !<, I did not test others), the generated test driver will have a line

```
use contains
```

which causes some issues because I do not have a module named contains

Daan

ps. Thanks for making FRUITPy, it made my life a bit easier :)

**Comment by acroucher** [comment]
hi Daan, thanks for reporting that.

Am I right in suspecting that your comment included the words 'module contains'? There was a bug in parse_test_module_name() which meant it would fail if there was a comment before the start of the module, which had the word 'module' in it.

I have just pushed a fix to the FRUITPy testing branch. Can you try that and let me know if it fixes your problem?

**Comment by DaanVanVugt** [comment]
Hi Adrian,

Yes you are completely right.
The newest testing branch seems to work just fine.

Thanks,
Daan

**Comment by acroucher** [comment]
Great. I've just merged that fix into the master branch.
