### ISSUE TITLE
FRUITPy integration into FOODiE. Some hints are necessary

### ISSUE THREAD

**Issue by szaghi** [acroucher/FRUITPy#9]
Dear Adrian,

I would like to try your FRUITPy for the tests facility of [FOODiE](https://github.com/Fortran-FOSS-Programmers/FOODiE). However, I think I will not have much time devoted to this aim. In particular, I think I cannot study in details fruit library, thus I come to you and your FRUITPy.

Can you explain why I will like to use your wrapper? Are the FRUITPy documentations compressed into its README and one-page-wiki, or are there other sources?

Thank you for sharing your work!

My best regards,
Stefano

**Comment by acroucher** [comment]
hi Stefano,

Yes, the FRUITPy documentation basically consists of the readme file, plus some stuff on the [wiki pages](https://github.com/acroucher/FRUITPy/wiki/FRUITPy-in-3-minutes) at the moment. My time is quite limited right now too!

The main reason you might want to use FRUITPy is to automatically create the driver program to run your unit tests. FRUITPy scans the unit test sources and detects test subroutines, and adds calls to them in the driver program source. FRUITPy will also build and run the tests and parse the FRUIT output.

FRUIT includes some Ruby tools for doing similar things. However I have no experience with Ruby and didn't manage to get them to work. I tend to use Python for pretty much all scripting so thought I would create a Python replacement for them.

**Comment by szaghi** [comment]
@acroucher thank you very much

> The main reason you might want to use FRUITPy is to automatically create the driver program to run your unit tests. FRUITPy scans the unit test sources and detects test subroutines, and adds calls to them in the driver program source. FRUITPy will also run the tests and parse the FRUIT output.

Amazing! I will try it

> FRUIT includes some Ruby tools for doing similar things. However I have no experience with Ruby and didn't manage to get them to work. I tend to use Python for pretty much all scripting so thought I would create a Python replacement for them.

Yes, it is curious, but many Fortran like us are more familiar with Python than other _similar_ interpretated languages... I am with you :-)

Thank you again.
